import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/Link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Basketball</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          API-BASKETBALL
        </h1>

        <p className={styles.description}>
          Basketball API stats and user interface experiment.
        </p>

        <div className={styles.grid}>

          <Link href="/">
            <a className={styles.card}>
              <h2>Players &rarr;</h2>
              <p>Players</p>
            </a>
          </Link>

          <Link href="/">
            <a className={styles.card}>
              <h2>Teams &rarr;</h2>
              <p>Teams</p>
            </a>
          </Link>

          <Link href="/">
            <a className={styles.card}>
              <h2>Stats &rarr;</h2>
              <p>Stats</p>
            </a>
          </Link>

          <Link href="/">
            <a className={styles.card}>
              <h2>About &rarr;</h2>
              <p>About</p>
            </a>
          </Link>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://amirardalan.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright © 2022 &mdash; Amir Ardalan
        </a>
      </footer>
    </div>
  )
}

export default Home
